import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DesktopNavbar from "@/components/navbar/DesktopNavbar";
import NavBar from "@/components/navbar/NavBar";
import NavbarContainer from "@/components/navbar/NavBarContainer";
import Post from "@/components/post/Post";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarContainer>
          <NavBar></NavBar>
        </NavbarContainer>
        {children}
        {<Post posts={[]}></Post>}
      </body>
    </html>
  );
}
